name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is set as stale due to no recent activity. Please bump if this is not correct'
        stale-pr-message: 'This pull request is set as stale due to no recent activity. Please bump if this is not correct'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
